#!/bin/sh

# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file or at least your compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

##############################################################################
##
##  Gradle start up script for POSIX generated by Gradle.
##
##  This file contains the default Gradle start up script that is typically
##  used in Gradle's distribution. It is a wrapper script that downloads the
##  Gradle distribution if it is not already present.
##
##############################################################################

# Attempt to locate a Java executable. If one is not found, print a helpful
# message and exit.
if [ -z "$JAVA_HOME" ]; then
  if command -v java >/dev/null 2>&1; then
    JAVA_HOME=$(dirname $(dirname $(readlink -f $(command -v java))))
  else
    echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH." >&2
    exit 1
  fi
fi

DIR="$(cd "$(dirname "$0")" && pwd)"
CLASSPATH="$DIR/gradle/wrapper/gradle-wrapper.jar"

if [ ! -f "$CLASSPATH" ]; then
  echo "Gradle wrapper JAR not found. Please run 'gradle wrapper' or download it manually." >&2
  exit 1
fi

java -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
